variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SSL_NO_VERIFY: "1"
  APP_NAME: "whitesnake-staffing-frontend"

include:
  - project: "ws-internal/gitlab-ci"
    ref: universal-chart-v1
    file: "app_templates/build.yaml"


build:
  extends: .build
  variables:
    PROD_IMAGE_NAME: "whitesnake-staffing-frontend-prod"
    DEV_IMAGE_NAME: "whitesnake-staffing-frontend-dev"
